// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Exception exception
// swagger:model Exception
type Exception struct {

	// attributes
	Attributes interface{} `json:"attributes,omitempty"`

	// code
	Code interface{} `json:"code,omitempty"`

	// handled
	Handled bool `json:"handled,omitempty"`

	// message
	// Required: true
	Message *string `json:"message"`

	// module
	// Max Length: 1024
	Module string `json:"module,omitempty"`

	// stacktrace
	Stacktrace ExceptionStacktrace `json:"stacktrace"`

	// type
	// Max Length: 1024
	Type string `json:"type,omitempty"`
}

// Validate validates this exception
func (m *Exception) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMessage(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateModule(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Exception) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

func (m *Exception) validateModule(formats strfmt.Registry) error {

	if swag.IsZero(m.Module) { // not required
		return nil
	}

	if err := validate.MaxLength("module", "body", string(m.Module), 1024); err != nil {
		return err
	}

	return nil
}

func (m *Exception) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	if err := validate.MaxLength("type", "body", string(m.Type), 1024); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Exception) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Exception) UnmarshalBinary(b []byte) error {
	var res Exception
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
