// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Mark mark
// swagger:model Mark
type Mark map[string]float64

// Validate validates this mark
func (m Mark) Validate(formats strfmt.Registry) error {
	return nil
}
