// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Process process
// swagger:model Process
type Process struct {

	// argv
	Argv []string `json:"argv"`

	// pid
	// Required: true
	Pid *int64 `json:"pid"`

	// ppid
	Ppid int64 `json:"ppid,omitempty"`

	// title
	// Max Length: 1024
	Title string `json:"title,omitempty"`
}

// Validate validates this process
func (m *Process) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArgv(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePid(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTitle(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Process) validateArgv(formats strfmt.Registry) error {

	if swag.IsZero(m.Argv) { // not required
		return nil
	}

	return nil
}

func (m *Process) validatePid(formats strfmt.Registry) error {

	if err := validate.Required("pid", "body", m.Pid); err != nil {
		return err
	}

	return nil
}

func (m *Process) validateTitle(formats strfmt.Registry) error {

	if swag.IsZero(m.Title) { // not required
		return nil
	}

	if err := validate.MaxLength("title", "body", string(m.Title), 1024); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Process) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Process) UnmarshalBinary(b []byte) error {
	var res Process
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
