// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5c87105dDecodeGithubComElasticApmServerModels(in *jlexer.Lexer, out *Process) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "argv":
			if in.IsNull() {
				in.Skip()
				out.Argv = nil
			} else {
				in.Delim('[')
				if out.Argv == nil {
					if !in.IsDelim(']') {
						out.Argv = make([]string, 0, 4)
					} else {
						out.Argv = []string{}
					}
				} else {
					out.Argv = (out.Argv)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Argv = append(out.Argv, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "pid":
			if in.IsNull() {
				in.Skip()
				out.Pid = nil
			} else {
				if out.Pid == nil {
					out.Pid = new(int64)
				}
				*out.Pid = int64(in.Int64())
			}
		case "ppid":
			out.Ppid = int64(in.Int64())
		case "title":
			out.Title = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5c87105dEncodeGithubComElasticApmServerModels(out *jwriter.Writer, in Process) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"argv\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Argv == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Argv {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"pid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Pid == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.Pid))
		}
	}
	if in.Ppid != 0 {
		const prefix string = ",\"ppid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Ppid))
	}
	if in.Title != "" {
		const prefix string = ",\"title\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Title))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Process) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5c87105dEncodeGithubComElasticApmServerModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Process) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5c87105dEncodeGithubComElasticApmServerModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Process) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5c87105dDecodeGithubComElasticApmServerModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Process) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5c87105dDecodeGithubComElasticApmServerModels(l, v)
}
