// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// RequestSocket request socket
// swagger:model requestSocket
type RequestSocket struct {

	// encrypted
	Encrypted bool `json:"encrypted,omitempty"`

	// remote address
	RemoteAddress string `json:"remote_address,omitempty"`
}

// Validate validates this request socket
func (m *RequestSocket) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *RequestSocket) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestSocket) UnmarshalBinary(b []byte) error {
	var res RequestSocket
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
