// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA7f3bcddDecodeGithubComElasticApmServerModels(in *jlexer.Lexer, out *StacktraceFrame) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "abs_path":
			out.AbsPath = string(in.String())
		case "colno":
			out.Colno = int64(in.Int64())
		case "context_line":
			out.ContextLine = string(in.String())
		case "filename":
			if in.IsNull() {
				in.Skip()
				out.Filename = nil
			} else {
				if out.Filename == nil {
					out.Filename = new(string)
				}
				*out.Filename = string(in.String())
			}
		case "function":
			out.Function = string(in.String())
		case "library_frame":
			out.LibraryFrame = bool(in.Bool())
		case "lineno":
			if in.IsNull() {
				in.Skip()
				out.Lineno = nil
			} else {
				if out.Lineno == nil {
					out.Lineno = new(int64)
				}
				*out.Lineno = int64(in.Int64())
			}
		case "module":
			out.Module = string(in.String())
		case "post_context":
			if in.IsNull() {
				in.Skip()
				out.PostContext = nil
			} else {
				in.Delim('[')
				if out.PostContext == nil {
					if !in.IsDelim(']') {
						out.PostContext = make([]string, 0, 4)
					} else {
						out.PostContext = []string{}
					}
				} else {
					out.PostContext = (out.PostContext)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.PostContext = append(out.PostContext, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "pre_context":
			if in.IsNull() {
				in.Skip()
				out.PreContext = nil
			} else {
				in.Delim('[')
				if out.PreContext == nil {
					if !in.IsDelim(']') {
						out.PreContext = make([]string, 0, 4)
					} else {
						out.PreContext = []string{}
					}
				} else {
					out.PreContext = (out.PreContext)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					v2 = string(in.String())
					out.PreContext = append(out.PreContext, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "vars":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Vars = make(map[string]interface{})
				} else {
					out.Vars = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v3 interface{}
					if m, ok := v3.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v3.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v3 = in.Interface()
					}
					(out.Vars)[key] = v3
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA7f3bcddEncodeGithubComElasticApmServerModels(out *jwriter.Writer, in StacktraceFrame) {
	out.RawByte('{')
	first := true
	_ = first
	if in.AbsPath != "" {
		const prefix string = ",\"abs_path\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AbsPath))
	}
	if in.Colno != 0 {
		const prefix string = ",\"colno\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Colno))
	}
	if in.ContextLine != "" {
		const prefix string = ",\"context_line\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ContextLine))
	}
	{
		const prefix string = ",\"filename\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Filename == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Filename))
		}
	}
	if in.Function != "" {
		const prefix string = ",\"function\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Function))
	}
	if in.LibraryFrame {
		const prefix string = ",\"library_frame\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.LibraryFrame))
	}
	{
		const prefix string = ",\"lineno\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Lineno == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.Lineno))
		}
	}
	if in.Module != "" {
		const prefix string = ",\"module\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Module))
	}
	{
		const prefix string = ",\"post_context\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.PostContext == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v4, v5 := range in.PostContext {
				if v4 > 0 {
					out.RawByte(',')
				}
				out.String(string(v5))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"pre_context\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.PreContext == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v6, v7 := range in.PreContext {
				if v6 > 0 {
					out.RawByte(',')
				}
				out.String(string(v7))
			}
			out.RawByte(']')
		}
	}
	if len(in.Vars) != 0 {
		const prefix string = ",\"vars\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('{')
			v8First := true
			for v8Name, v8Value := range in.Vars {
				if v8First {
					v8First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v8Name))
				out.RawByte(':')
				if m, ok := v8Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v8Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v8Value))
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StacktraceFrame) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA7f3bcddEncodeGithubComElasticApmServerModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StacktraceFrame) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA7f3bcddEncodeGithubComElasticApmServerModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StacktraceFrame) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA7f3bcddDecodeGithubComElasticApmServerModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StacktraceFrame) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA7f3bcddDecodeGithubComElasticApmServerModels(l, v)
}
