// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TransactionsPayloadTransactions transactions payload transactions
// swagger:model transactionsPayloadTransactions
type TransactionsPayloadTransactions []*Transaction

// Validate validates this transactions payload transactions
func (m TransactionsPayloadTransactions) Validate(formats strfmt.Registry) error {
	var res []error

	iTransactionsPayloadTransactionsSize := int64(len(m))

	if err := validate.MinItems("", "body", iTransactionsPayloadTransactionsSize, 1); err != nil {
		return err
	}

	for i := 0; i < len(m); i++ {

		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {

			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
