// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TransactionSpanCountDropped transaction span count dropped
// swagger:model transactionSpanCountDropped
type TransactionSpanCountDropped struct {

	// total
	Total float64 `json:"total,omitempty"`
}

// Validate validates this transaction span count dropped
func (m *TransactionSpanCountDropped) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TransactionSpanCountDropped) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionSpanCountDropped) UnmarshalBinary(b []byte) error {
	var res TransactionSpanCountDropped
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
