// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDe023d17DecodeGithubComElasticApmServerModels(in *jlexer.Lexer, out *TransactionSpanCount) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "dropped":
			if in.IsNull() {
				in.Skip()
				out.Dropped = nil
			} else {
				if out.Dropped == nil {
					out.Dropped = new(TransactionSpanCountDropped)
				}
				easyjsonDe023d17DecodeGithubComElasticApmServerModels1(in, &*out.Dropped)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDe023d17EncodeGithubComElasticApmServerModels(out *jwriter.Writer, in TransactionSpanCount) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Dropped != nil {
		const prefix string = ",\"dropped\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjsonDe023d17EncodeGithubComElasticApmServerModels1(out, *in.Dropped)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TransactionSpanCount) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDe023d17EncodeGithubComElasticApmServerModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TransactionSpanCount) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDe023d17EncodeGithubComElasticApmServerModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TransactionSpanCount) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDe023d17DecodeGithubComElasticApmServerModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TransactionSpanCount) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDe023d17DecodeGithubComElasticApmServerModels(l, v)
}
func easyjsonDe023d17DecodeGithubComElasticApmServerModels1(in *jlexer.Lexer, out *TransactionSpanCountDropped) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "total":
			out.Total = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDe023d17EncodeGithubComElasticApmServerModels1(out *jwriter.Writer, in TransactionSpanCountDropped) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Total != 0 {
		const prefix string = ",\"total\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.Total))
	}
	out.RawByte('}')
}
